export const GET_SUBJECT = "GET_SUBJECT";
export const GET_DETAIL_SUBJECT = "GET_DETAIL_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
